$terminal = kitty
$browser = firefox
$code = code
$menu = ~/.config/rofi/launcher.sh
$fileManager = nautilus
$wifiManager = ~/.config/hypr/scripts/wifimananger.sh
$wifiDisconnect = ~/.config/hypr/scripts/wifidisconnect.sh
$rofiLogout = ~/.config/hypr/scripts/powermenu.sh